# -*- coding: utf-8 -*-
"""MLproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWrCpVIT8Fo7bLqA7p24P8c_R__0xZAn

Import Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

"""Import Dataset for Model"""

df=pd.read_csv("/content/customer_personality_dataset (1).csv")

"""Data Analysis ⚛"""

df.info()

df.head()

df.tail()

df.describe()

print(df.columns)

df.isnull().sum()

sns.distplot(df['Annual_Income'])
plt.show()

print(df.duplicated().sum())

for column in df.columns:

    unique_features = df[column].unique()

    print(f"Unique values in '{column}'-")
    print(unique_features)
    print("\n")

"""Data Preprocessing



"""

df.drop(columns='Customer_ID', inplace=True)
df = pd.get_dummies(df, columns=['Gender','Marital_Status','Education','Occupation','Preferred_Channel'], drop_first=True)

"""Exploratory Data Analysis (EDA)"""

corr = df.corr()
print(corr['Risk_Taking_Score'].sort_values(ascending=False)[:5])

plt.figure(figsize=(12, 8))
sns.heatmap(corr, annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5)
plt.title('Feature Correlation Heatmap')
plt.show()

"""Feature Engineering"""

df['Fashion_to_Total'] = df['Category_Fashion_Spend'] / df['Total_Spend']
df['Electronics_to_Total'] = df['Category_Electronics_Spend'] / df['Total_Spend']
df['Grocery_to_Total'] = df['Category_Grocery_Spend'] / df['Total_Spend']
df['Income_per_Person'] = df['Annual_Income'] / (df['Children'] + 1)
df['Age_Group'] = pd.cut(df['Age'], bins=[17,30,50,100], labels=['Young','Adult','Senior'])
df = pd.get_dummies(df, columns=['Age_Group'], drop_first=True)

sns.distplot(df['Income_per_Person'])
plt.show()

print(df.columns)

"""Train-Test Split"""

X = df.drop('Risk_Taking_Score', axis=1)
y = df['Risk_Taking_Score']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

"""Data Standardization"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

"""Model Building"""

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)
rf.fit(X_train_scaled, y_train)

"""Hyperparameter Tuning with Cross-Validation

"""

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10]
}

grid_rf = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='f1_macro '
)


grid_rf.fit(X_train_scaled, y_train)


best_rf = grid_rf.best_estimator_
print("Best RandomForest params:", grid_rf.best_params_)

"""Model Evaluation"""

from sklearn.metrics import accuracy_score, f1_score
y_pred = best_rf.predict(X_test_scaled)
print("Random Forest - Accuracy:", accuracy_score(y_test, y_pred),
      "Macro F1:", f1_score(y_test, y_pred, average='macro'))

"""Insights and Interpretation"""

importances = best_rf.feature_importances_
indices = np.argsort(importances)[::-1]
top_feat = [(X.columns[i], importances[i]) for i in indices[:8]]
print("Top features by RF importance:", top_feat)